<?php
	define( 'INSTAGRAM_APP_ID', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );
	define( 'INSTAGRAM_APP_SECRET', 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );
	define( 'INSTAGRAM_APP_REDIRECT_URI', 'https://EXAMPLE.com/' );