<?php
	define( 'INSTAGRAM_APP_ID', 'YOUR_INSTAGRAM_APP_ID' );
	define( 'INSTAGRAM_APP_SECRET', 'YOUR_INSTAGRAM_APP_SECRET' );
	define( 'INSTAGRAM_APP_REDIRECT_URI', 'YOUR_INSTAGRAM_APP_REDIRECT_URI' );